plantilla = {
    "Fecha": {""},
    "Hora": {""},
    "Lugar": {""},
    "Testigos": {""},
    "AseguradoA": {"NOMBRE": "", "Apellidos": "", "Direcci\u00f3n": "", "C\u00f3digo Postal": "", "Pa\u00eds": "", "Tel. o E-mail": ""}, 
    "AseguradoraA": {"NOMBRE": "", "N.\u00ba de p\u00f3liza": "", "N.\u00ba de Carta Verde": "", "Certificado": "", "Agencia (oficina o corredor)": "", "Nombre": "", "Direcci\u00f3n": "", "Pa\u00eds": "", "Tel. o E-mail": ""},
    "ConductorA": {"NOMBRE": "", "Apellidos": "", "Fecha de nacimiento": "", "Direcci\u00f3n": "", "Pa\u00eds": "", "Tel. o E-mail": "", "Permiso de conducir n.\u00ba": "", ")": "", "Permiso v\u00e1lido hasta": ""},
    "Vehiculo_motor_A": {"Marca, modelo": "", "Matrícula (o bastidor)": "", "País de matrícula": ""},
    "Remolque_A":{"Matrícula (o bastidor)": "", "País de matrícula": ""},

    "Circ1_A": {"Concepto":"Está estacionado/parado", "Estado":"unselected"},
    "Circ2_A": {"Concepto":"Salia de un estacionamiento/abriendo puerta", "Estado":"unselected"},
    "Circ3_A": {"Concepto":"Iba a estacionar", "Estado":"unselected"},
    "Circ4_A": {"Concepto":"Salía de un aparcamiento, de un lugar privado o un camino de tierra", "Estado":"unselected"},
    "Circ5_A": {"Concepto":"Entrada a un aparcamiento, de un lugar privado o un camino de tierra", "Estado":"unselected"},
    "Circ6_A": {"Concepto":"Entrada a una plaza de sentido giratorio", "Estado":"unselected"},
    "Circ7_A": {"Concepto":"Circulaba a una plaza de sentido giratorio", "Estado":"unselected"},
    "Circ8_A": {"Concepto":"Colisiono en la parte de atras al otro vehiculo que circulaba en el mismo sentido y en el mismo carril", "Estado":"unselected"},
    "Circ9_A": {"Concepto":"Circulaba en el mismo sentido y distinto carril", "Estado":"unselected"},
    "Circ10_A": {"Concepto":"Cambiaba de carril", "Estado":"unselected"},
    "Circ11_A": {"Concepto":"Adelantaba", "Estado":"unselected"},
    "Circ12_A": {"Concepto":"Giraba a la derecha", "Estado":"unselected"},
    "Circ13_A": {"Concepto":"Daba marcha atras", "Estado":"unselected"},
    "Circ15_A": {"Concepto":"Invadia la parte reservada a la circulacion en sentido inverso", "Estado":"unselected"},
    "Circ16_A": {"Concepto":"Venia de la derecha(en un cruce)", "Estado":"unselected"},
    "Circ17_A": {"Concepto":"No respeto la señal de preferencia o semaforo en rojo", "Estado":"unselected"},
    "Nºcasillas_A": {""},

    "AseguradoB": {"NOMBRE": "", "Apellidos": "", "Direcci\u00f3n": "", "C\u00f3digo Postal": "", "Pa\u00eds": "", "Tel. o E-mail": ""}, 
    "AseguradoraB": {"NOMBRE": "", "N.\u00ba de p\u00f3liza": "", "N.\u00ba de Carta Verde": "", "Certificado": "", "Agencia (oficina o corredor)": "", "Nombre": "", "Direcci\u00f3n": "", "Pa\u00eds": ""}, 
    "ConductorB": {"NOMBRE": "", "Apellidos": "", "Fecha de nacimiento": "", "Direcci\u00f3n": "", "Pa\u00eds": "", "Tel. o E-mail": "", "Permiso de conducir n.\u00ba": "", "Permiso v\u00e1lido hasta": ""}, 
    "Vehiculo_motor_B": {"Matrícula (o bastidor)": "", "Marca, modelo": "", "País de matrícula": ""},
    "Remolque_B":{"Matrícula (o bastidor)": "", "País de matrícula": ""},

    "Circ1_B": {"Concepto":"Está estacionado/parado", "Estado":"unselected"},
    "Circ2_B": {"Concepto":"Salia de un estacionamiento/abriendo puerta", "Estado":"unselected"},
    "Circ3_B": {"Concepto":"Iba a estacionar", "Estado":"unselected"},
    "Circ4_B": {"Concepto":"Salía de un aparcamiento, de un lugar privado o un camino de tierra", "Estado":"unselected"},
    "Circ5_B": {"Concepto":"Entrada a un aparcamiento, de un lugar privado o un camino de tierra", "Estado":"unselected"},
    "Circ6_B": {"Concepto":"Entrada a una plaza de sentido giratorio", "Estado":"unselected"},
    "Circ7_B": {"Concepto":"Circulaba a una plaza de sentido giratorio", "Estado":"unselected"},
    "Circ8_B": {"Concepto":"Colisiono en la parte de atras al otro vehiculo que circulaba en el mismo sentido y en el mismo carril", "Estado":"unselected"},
    "Circ9_B": {"Concepto":"Circulaba en el mismo sentido y distinto carril", "Estado":"unselected"},
    "Circ10_B": {"Concepto":"Cambiaba de carril", "Estado":"unselected"},
    "Circ11_B": {"Concepto":"Adelantaba", "Estado":"unselected"},
    "Circ12_B": {"Concepto":"Giraba a la derecha", "Estado":"unselected"},
    "Circ13_B": {"Concepto":"Daba marcha atras", "Estado":"unselected"},
    "Circ15_B": {"Concepto":"Invadia la parte reservada a la circulacion en sentido inverso", "Estado":"unselected"},
    "Circ16_B": {"Concepto":"Venia de la derecha(en un cruce)", "Estado":"unselected"},
    "Circ17_B": {"Concepto":"No respeto la señal de preferencia o semaforo en rojo", "Estado":"unselected"},
    "Nºcasillas_B": {}

}


plantilla2 = {
    "FECHA": {""},
    "HORA": {""},
    "LUGAR": {""},
    "TESTIGOS": {""},
    "VEHICULO_A":{
        "ASEGURADO_A": {"NOMBRE": "", "APELLIDOS": "", "DIRECCION": "", "CODIGO_POSTAL": "", "PAIS": "", "TEL. O E-MAIL": ""}, 
        "ASEGURADORA_A": {"NOMBRE": "", "Nº DE POLIZA": "", "N.º DE CARTA VERDE": "", "CERTIFICADO": "", "AGENCIA (OFICINA O CORREDOR)": "", "NOMBRE_AGENCIA": "", "DIRECCION_AGENCIA": "", "PAIS_AGENCIA": "", "TEL. O E-MAIL AGENCIA": ""},
        "CONDUCTOR_A": {"NOMBRE": "", "APELLIDOS": "", "FECHA DE NACIMIENTO": "", "DIRECCION": "", "PAIS": "", "TEL. o E-MAIL": "", "Nº PERMISO DE CONDUCIR": "", "CATEGORIA(A,B, ...)": "", "PERMISO VALIDO HASTA": ""}, 
        
        "CIRC1": {"CONCEPTO":"Está estacionado/parado", "ESTADO":"unselected"},
        "CIRC2": {"CONCEPTO":"Salia de un estacionamiento/abriendo puerta", "ESTADO":"unselected"},
        "CIRC3": {"CONCEPTO":"Salia de un estacionamiento/abriendo puerta", "ESTADO":"unselected"},
        "CIRC4": {"CONCEPTO":"Salía de un aparcamiento, de un lugar privado o un camino de tierra", "ESTADO":"unselected"},
        "CIRC5": {"CONCEPTO":"Entrada a un aparcamiento, de un lugar privado o un camino de tierra", "ESTADO":"unselected"},
        "CIRC6": {"CONCEPTO":"Entrada a una plaza de sentido giratorio", "ESTADO":"unselected"},
        "CIRC7": {"CONCEPTO":"Circulaba a una plaza de sentido giratorio", "ESTADO":"unselected"},
        "CIRC8": {"CONCEPTO":"Colisiono en la parte de atras al otro vehiculo que circulaba en el mismo sentido y en el mismo carril", "ESTADO":"unselected"},
        "CIRC9": {"CONCEPTO":"Circulaba en el mismo sentido y distinto carril", "ESTADO":"unselected"},
        "CIRC10": {"CONCEPTO":"Cambiaba de carril", "ESTADO":"unselected"},
        "CIRC11": {"CONCEPTO":"Adelantaba", "ESTADO":"unselected"},
        "CIRC12": {"CONCEPTO":"Giraba a la derecha", "ESTADO":"unselected"},
        "CIRC13": {"CONCEPTO":"Daba marcha atras", "ESTADO":"unselected"},
        "CIRC14": {"CONCEPTO":"Daba marcha atras", "ESTADO":"unselected"},
        "CIRC15": {"CONCEPTO":"Invadia la parte reservada a la circulacion en sentido inverso", "ESTADO":"unselected"},
        "CIRC16": {"CONCEPTO":"Venia de la derecha(en un cruce)", "ESTADO":"unselected"},
        "CIRC17": {"CONCEPTO":"No respeto la señal de preferencia o semaforo en rojo", "ESTADO":"unselected"},
        "Nº_CASILLAS": {""}
    },
    "VEHICULO_B":{
        "ASEGURADO_B": {"NOMBRE": "", "APELLIDOS": "", "DIRECCION": "", "CODIGO POSTAL": "", "PAIS": "", "TEL. O E-MAIL": ""}, 
        "ASEGURADORA_B": {"NOMBRE": "", "Nº DE POLIZA": "", "N.º DE CARTA VERDE": "", "CERTIFICADO": "", "AGENCIA (OFICINA O CORREDOR)": "", "NOMBRE_AGENCIA": "", "DIRECCION_AGENCIA": "", "PAIS_AGENCIA": "", "TEL. O E-MAIL AGENCIA": ""},
        "CONDUCTOR_B": {"NOMBRE": "", "APELLIDOS": "", "FECHA DE NACIMIENTO": "", "DIRECCION": "", "PAIS": "", "TEL. o E-MAIL": "", "Nº PERMISO DE CONDUCIR": "", "CATEGORIA(A,B,...)": "", "PERMISO VALIDO HASTA": ""}, 
    
        "CIRC1": {"CONCEPTO":"Está estacionado/parado", "ESTADO":"unselected"},
        "CIRC2": {"CONCEPTO":"Salia de un estacionamiento/abriendo puerta", "ESTADO":"unselected"},
        "CIRC4": {"CONCEPTO":"Salía de un aparcamiento, de un lugar privado o un camino de tierra", "ESTADO":"unselected"},
        "CIRC5": {"CONCEPTO":"Entrada a un aparcamiento, de un lugar privado o un camino de tierra", "ESTADO":"unselected"},
        "CIRC6": {"CONCEPTO":"Entrada a una plaza de sentido giratorio", "ESTADO":"unselected"},
        "CIRC7": {"CONCEPTO":"Circulaba a una plaza de sentido giratorio", "ESTADO":"unselected"},
        "CIRC8": {"CONCEPTO":"Colisiono en la parte de atras al otro vehiculo que circulaba en el mismo sentido y en el mismo carril", "ESTADO":"unselected"},
        "CIRC9": {"CONCEPTO":"Circulaba en el mismo sentido y distinto carril", "ESTADO":"unselected"},
        "CIRC10": {"CONCEPTO":"Cambiaba de carril", "ESTADO":"unselected"},
        "CIRC11": {"CONCEPTO":"Adelantaba", "ESTADO":"unselected"},
        "CIRC12": {"CONCEPTO":"Giraba a la derecha", "ESTADO":"unselected"},
        "CIRC13": {"CONCEPTO":"Daba marcha atras", "ESTADO":"unselected"},
        "CIRC14": {"CONCEPTO":"Daba marcha atras", "ESTADO":"unselected"},
        "CIRC15": {"CONCEPTO":"Invadia la parte reservada a la circulacion en sentido inverso", "ESTADO":"unselected"},
        "CIRC16": {"CONCEPTO":"Venia de la derecha(en un cruce)", "ESTADO":"unselected"},
        "CIRC17": {"CONCEPTO":"No respeto la señal de preferencia o semaforo en rojo", "ESTADO":"unselected"},
        "Nº_CASILLAS": {""}
    }
}

mapeo = {
    "Fecha": "Fecha",
    "Hora": "Hora",
    "Lugar": "Lugar",
    "Testigos": "Testigos",
    
    "AseguradoA": {"NOMBRE": "NOMBRE", "Apellidos": "Apellidos", "Direcci\u00f3n": "Direcci\u00f3n", "C\u00f3digo Postal": "C\u00f3digo Postal", "Pa\u00eds": "Pa\u00eds", "Tel. o E-mail": "Tel. o E-mail"}, 
    "AseguradoraA": {"NOMBRE": "NOMBRE", "N.\u00ba de p\u00f3liza": "N.\u00ba de p\u00f3liza", "N.\u00ba de Carta Verde": "N.\u00ba de Carta Verde", "Certificado": "Certificado", "Agencia (oficina o corredor)": "Agencia (oficina o corredor)", "Nombre": "Nombre", "Direcci\u00f3n": "Direcci\u00f3n", "Pa\u00eds": "Pa\u00eds", "Tel. o E-mail": "Tel. o E-mail"},
    "ConductorA": {"NOMBRE": "NOMBRE", "Apellidos": "Apellidos", "Fecha de nacimiento": "Fecha de nacimiento", "Direcci\u00f3n": "Direcci\u00f3n", "Pa\u00eds": "Pa\u00eds", "Tel. o E-mail": "Tel. o E-mail", "Permiso de conducir n.\u00ba": "Permiso de conducir n.\u00ba", ")": ")", "Permiso v\u00e1lido hasta": "Permiso v\u00e1lido hasta"}, 
    "Vehiculo_motor_A": {"Marca, modelo": "Marca, modelo", "Matrícula (o bastidor)": "Matrícula (o bastidor)", "País de matrícula": "País de matrícula"},
    "Remolque_A":{"Matrícula (o bastidor)": "Matrícula (o bastidor)", "País de matrícula": "País de matrícula"},

    "Circ1_A": {"Concepto":"Concepto", "Estado":""},
    "Circ2_A": {"Concepto":"Concepto", "Estado":""},
    "Circ3_A": {"Concepto":"Concepto", "Estado":""},
    "Circ4_A": {"Concepto":"Concepto", "Estado":""},
    "Circ5_A": {"Concepto":"Concepto", "Estado":""},
    "Circ6_A": {"Concepto":"Concepto", "Estado":""},
    "Circ7_A": {"Concepto":"Concepto", "Estado":""},
    "Circ8_A": {"Concepto":"Concepto", "Estado":""},
    "Circ9_A": {"Concepto":"Concepto", "Estado":""},
    "Circ10_A": {"Concepto":"Concepto", "Estado":""},
    "Circ11_A": {"Concepto":"Concepto", "Estado":""},
    "Circ12_A": {"Concepto":"Concepto", "Estado":""},
    "Circ13_A": {"Concepto":"Concepto", "Estado":""},
    "Circ14_A": {"Concepto":"Concepto", "Estado":""},
    "Circ15_A": {"Concepto":"Concepto", "Estado":""},
    "Circ16_A": {"Concepto":"Concepto", "Estado":""},
    "Circ17_A": {"Concepto":"Concepto", "Estado":""},
    "Nºcasillas_A":"N\u00b0casillas_A",

    "AseguradoB": {"NOMBRE": "NOMBRE", "Apellidos": "Apellidos", "Direcci\u00f3n": "Direcci\u00f3n", "C\u00f3digo Postal": "C\u00f3digo Postal", "Pa\u00eds": "Pa\u00eds", "Tel. o E-mail": "Tel. o E-mail"}, 
    "AseguradoraB": {"NOMBRE": "NOMBRE", "N.\u00ba de p\u00f3liza": "N.\u00ba de p\u00f3liza", "N.\u00ba de Carta Verde": "N.\u00ba de Carta Verde", "Certificado": "Certificado", "Agencia (oficina o corredor)": "Agencia (oficina o corredor)", "Nombre": "Nombre", "Direcci\u00f3n": "Direcci\u00f3n", "Pa\u00eds": "Pa\u00eds"}, 
    "ConductorB": {"NOMBRE": "NOMBRE", "Apellidos": "Apellidos", "Fecha de nacimiento": "Fecha de nacimiento", "Direcci\u00f3n": "Direcci\u00f3n", "Pa\u00eds": "Pa\u00eds", "Tel. o E-mail": "Tel. o E-mail", "Permiso de conducir n.\u00ba": "Permiso de conducir n.\u00ba", "Permiso v\u00e1lido hasta": "Permiso v\u00e1lido hasta"}, 
    "Vehiculo_motor_B": {"Marca, modelo": "Marca, modelo", "Matrícula (o bastidor)": "Matrícula (o bastidor)", "País de matrícula": "País de matrícula"},
    "Remolque_B":{"Matrícula (o bastidor)": "Matrícula (o bastidor)", "País de matrícula": "País de matrícula"},

    "Circ1_B": {"Concepto":"Concepto", "Estado":""},
    "Circ2_B": {"Concepto":"Concepto", "Estado":""},
    "Circ3_B": {"Concepto":"Concepto", "Estado":""},
    "Circ4_B": {"Concepto":"Concepto", "Estado":""},
    "Circ5_B": {"Concepto":"Concepto", "Estado":""},
    "Circ6_B": {"Concepto":"Concepto", "Estado":""},
    "Circ7_B": {"Concepto":"Concepto", "Estado":""},
    "Circ8_B": {"Concepto":"Concepto", "Estado":""},
    "Circ9_B": {"Concepto":"Concepto", "Estado":""},
    "Circ10_B": {"Concepto":"Concepto", "Estado":""},
    "Circ11_B": {"Concepto":"Concepto", "Estado":""},
    "Circ12_B": {"Concepto":"Concepto", "Estado":""},
    "Circ13_B": {"Concepto":"Concepto", "Estado":""},
    "Circ14_B": {"Concepto":"Concepto", "Estado":""},
    "Circ15_B": {"Concepto":"Concepto", "Estado":""},
    "Circ16_B": {"Concepto":"Concepto", "Estado":""},
    "Circ17_B": {"Concepto":"Concepto", "Estado":""},
    "Nºcasillas_B":"N\u00b0casillas_B"
    
}

mapeo2 = {

    "Fecha": "FECHA",
    "Hora" :  "HORA",
    "Lugar": "LUGAR",
    "Testigos": "TESTIGOS",

    "AseguradoA": "ASEGURADO_A",
    "AseguradoraA": "ASEGURADORA_A",
    "ConductorA": "CONDUCTOR_A",
    "Vehiculo_motor_A": "VEHICULO_MOTOR_A",
    "Remolque_A": "REMOLQUE_A",

    "AseguradoB": "ASEGURADO_B",
    "AseguradoraB": "ASEGURADORA_B",
    "ConductorB": "CONDUCTOR_B",
    "Vehiculo_motor_B": "VEHICULO_MOTOR_B",
    "Remolque_B": "REMOLQUE_B",

    "NOMBRE": "NOMBRE", "Apellidos": "APELLIDOS", "Direcci\u00f3n": "DIRECCION", "C\u00f3digo Postal": "CODIGO POSTAL", "Pa\u00eds": "PAIS", "Tel. o E-mail": "TEL. O E-MAIL",
    "NOMBRE": "NOMBRE_ASEGURADORA", "N.\u00ba de p\u00f3liza": "N.º DE POLIZA", "N.\u00ba de Carta Verde": "N.º DE CARTA VERDE", "Certificado": "CERTIFICADO", "Agencia (oficina o corredor)": "AGENCIA (OFICINA O CORREDOR)", "Nombre": "NOMBRE_ASEGURADOR", "Direcci\u00f3n": "DIRECCION", "Pa\u00eds": "PAIS", "Tel. o E-mail": "TEL. O E-MAIL",
    "NOMBRE": "NOMBRE", "Apellidos": "APELLIDOS", "Fecha de nacimiento": "FECHA DE NACIMIENTO", "Direcci\u00f3n": "DIRECCION", "Pa\u00eds": "PAIS", "Tel. o E-mail": "TEL. o E-MAIL", "Permiso de conducir n.\u00ba": "PERMISO DE CONDUCIR n.\u00ba", ")": "CATEGORIA (A, B, ...)", "Categoría (A, B, ...)": "CATEGORÍA (A, B, ...)", "Permiso v\u00e1lido hasta": "PERMISO VALIDO HASTA", 
    "Marca, modelo": "MARCA, MODELO", "Matrícula (o bastidor)": "MATRICULA (O BASTIDOR)", "País de matrícula": "PAIS DE MATRICULA",
    "Matrícula (o bastidor)": "MATRICULA (O BASTIDOR)", "País de matrícula": "PAIS DE MATRICULA",

    "Circ1_A": "CIRC1_A",
    "Circ2_A": "CIRC2_A",
    "Circ3_A": "CIRC3_A",
    "Circ4_A": "CIRC4_A",
    "Circ5_A": "CIRC5_A",
    "Circ6_A": "CIRC6_A",
    "Circ7_A": "CIRC7_A",
    "Circ8_A": "CIRC8_A",
    "Circ9_A": "CIRC9_A",
    "Circ10_A": "CIRC10_A",
    "Circ11_A": "CIRC11_A",
    "Circ12_A": "CIRC12_A",
    "Circ13_A": "CIRC13_A",
    "Circ14_A": "CIRC14_A",
    "Circ15_A": "CIRC15_A",
    "Circ16_A": "CIRC16_A",
    "Circ17_A": "CIRC17_A",

    "Circ1_B": "CIRC1_B",
    "Circ2_B": "CIRC2_B",
    "Circ3_B": "CIRC3_B",
    "Circ4_B": "CIRC4_B",
    "Circ5_B": "CIRC5_B",
    "Circ6_B": "CIRC6_B",
    "Circ7_B": "CIRC7_B",
    "Circ8_B": "CIRC8_B",
    "Circ9_B": "CIRC9_B",
    "Circ10_B": "CIRC10_B",
    "Circ11_B": "CIRC11_B",
    "Circ12_B": "CIRC12_B",
    "Circ13_B": "CIRC13_B",
    "Circ14_B": "CIRC14_B",
    "Circ15_B": "CIRC15_B",
    "Circ16_B": "CIRC16_B",
    "Circ17_B": "CIRC17_B",

    "Concepto":"CONCEPTO", "Estado":"ESTADO",

    "Nºcasillas_A": "NºCASILLAS_A",
    "Nºcasillas_B": "NºCASILLAS_B"

}

